controller_manager: #the name of the package that has the built_in nodes inside
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    

    joint_state_broadcaster: 
      type: joint_state_broadcaster/JointStateBroadcaster #built_in node inside controller_manager

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController  #built_in node inside controller_manager


simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint
